import images from '../assets/images';

export const data = [
  {
    id: 1,
    name: 'Americano',
    category: 'Americano',
    img: images.americano_pic_1_square(),
    favourite: false,
    quantity: 1,
  },
  {
    id: 2,
    name: 'Americano',
    category: 'Americano',
    img: images.americano_pic_2_square(),
    favourite: false,
    quantity: Number(1),
  },
  {
    id: 3,
    name: 'Americano',
    category: 'Americano',
    img: images.americano_pic_3_square(),
    favourite: false,
    quantity: Number(1),
  },
  {
    id: 4,
    name: 'Black Coffee',
    category: 'blackcoffee',
    img: images.black_coffee_pic_1_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 5,
    name: 'Black Coffee',
    category: 'blackcoffee',
    img: images.black_coffee_pic_2_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 6,
    name: 'Black Coffee',
    category: 'blackcoffee',
    img: images.black_coffee_pic_3_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 7,
    name: 'Cappuccino',
    category: 'cappuccino',
    img: images.cappuccino_pic_1_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 8,
    name: 'Cappuccino',
    category: 'cappuccino',
    img: images.cappuccino_pic_2_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 9,
    name: 'Cappuccino',
    category: 'cappuccino',
    img: images.cappuccino_pic_3_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 10,
    name: 'Espresso',
    category: 'espresso',
    img: images.espresso_pic_1_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 11,
    name: 'Espresso',
    category: 'espresso',
    img: images.espresso_pic_2_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 12,
    name: 'Espresso',
    category: 'espresso',
    img: images.espresso_pic_3_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 13,
    name: 'Latte',
    category: 'latte',
    img: images.espresso_pic_1_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 14,
    name: 'Latte',
    category: 'latte',
    img: images.espresso_pic_2_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 15,
    name: 'Latte',
    category: 'latte',
    img: images.espresso_pic_3_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 16,
    name: 'Macchiato',
    category: 'macchiato',
    img: images.macchiato_pic_1_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 17,
    name: 'Macchiato',
    category: 'macchiato',
    img: images.macchiato_pic_2_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 18,
    name: 'Macchiato',
    category: 'macchiato',
    img: images.macchiato_pic_3_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 19,
    name: 'Arabica Coffee',
    category: 'arabicacoffee',
    img: images.arabica_coffee_beans_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 20,
    name: 'Excelsa Coffee',
    category: 'excelsacoffee',
    img: images.excelsa_coffee_beans_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 21,
    name: 'Liberica Coffee',
    category: 'libericacoffee',
    img: images.liberica_coffee_beans_square(),
    favourite: false,
    quantity: Number(0),
  },
  {
    id: 22,
    name: 'Robusta Coffee',
    category: 'robustacoffee',
    img: images.robusta_coffee_beans_square(),
    favourite: false,
    quantity: Number(0),
  },
];
